package com.capa.datos;
// Generated 29-mar-2017 0:19:52 by Hibernate Tools 4.3.1

import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TCabecera generated by hbm2java
 */
public class TCabecera implements java.io.Serializable {

	private Integer CSerial;
	private TLugarGeografico TLugarGeografico;
	private String CNombreProyecto;
	private String CAmie;
	private String CZona;
	private Date CFechaEntrega;
	private Date CFechaInicio;
	private Date CFechaElaboracionInforme;
	private String sector;
	private String circuito;
	private byte[] CFotoGeneral;
	private byte[] CCroquis;
	private Set TFichaDs = new HashSet(0);

	public TCabecera() {
	}

	public TCabecera(TLugarGeografico TLugarGeografico) {
		this.TLugarGeografico = TLugarGeografico;
	}

	public TCabecera(TLugarGeografico TLugarGeografico, String CNombreProyecto, String CAmie, String CZona,
			Date CFechaEntrega, Date CFechaInicio, Date CFechaElaboracionInforme, byte[] CFotoGeneral, byte[] CCroquis,
			Set TFichaDs, String sector, String circuito) {
		this.TLugarGeografico = TLugarGeografico;
		this.CNombreProyecto = CNombreProyecto;
		this.CAmie = CAmie;
		this.CZona = CZona;
		this.CFechaEntrega = CFechaEntrega;
		this.CFechaInicio = CFechaInicio;
		this.CFechaElaboracionInforme = CFechaElaboracionInforme;
		this.CFotoGeneral = CFotoGeneral;
		this.CCroquis = CCroquis;
		this.TFichaDs = TFichaDs;
		this.sector = sector;
		this.circuito = circuito;
	}

	public Integer getCSerial() {
		return this.CSerial;
	}

	public void setCSerial(Integer CSerial) {
		this.CSerial = CSerial;
	}

	public TLugarGeografico getTLugarGeografico() {
		return this.TLugarGeografico;
	}

	public void setTLugarGeografico(TLugarGeografico TLugarGeografico) {
		this.TLugarGeografico = TLugarGeografico;
	}

	public String getCNombreProyecto() {
		return this.CNombreProyecto;
	}

	public void setCNombreProyecto(String CNombreProyecto) {
		this.CNombreProyecto = CNombreProyecto;
	}

	public String getCAmie() {
		return this.CAmie;
	}

	public void setCAmie(String CAmie) {
		this.CAmie = CAmie;
	}

	public String getCZona() {
		return this.CZona;
	}

	public void setCZona(String CZona) {
		this.CZona = CZona;
	}

	public Date getCFechaEntrega() {
		return this.CFechaEntrega;
	}

	public void setCFechaEntrega(Date CFechaEntrega) {
		this.CFechaEntrega = CFechaEntrega;
	}

	public Date getCFechaInicio() {
		return this.CFechaInicio;
	}

	public void setCFechaInicio(Date CFechaInicio) {
		this.CFechaInicio = CFechaInicio;
	}

	public Date getCFechaElaboracionInforme() {
		return this.CFechaElaboracionInforme;
	}

	public void setCFechaElaboracionInforme(Date CFechaElaboracionInforme) {
		this.CFechaElaboracionInforme = CFechaElaboracionInforme;
	}

	public byte[] getCFotoGeneral() {
		return this.CFotoGeneral;
	}

	public void setCFotoGeneral(byte[] CFotoGeneral) {
		this.CFotoGeneral = CFotoGeneral;
	}

	public byte[] getCCroquis() {
		return this.CCroquis;
	}

	public void setCCroquis(byte[] CCroquis) {
		this.CCroquis = CCroquis;
	}

	public Set getTFichaDs() {
		return this.TFichaDs;
	}

	public void setTFichaDs(Set TFichaDs) {
		this.TFichaDs = TFichaDs;
	}

	public String getSector() {
		return sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	public String getCircuito() {
		return circuito;
	}

	public void setCircuito(String circuito) {
		this.circuito = circuito;
	}

	@Override
	public String toString() {
		return "TCabecera [CSerial=" + CSerial + ", TLugarGeografico=" + TLugarGeografico + ", CNombreProyecto="
				+ CNombreProyecto + ", CAmie=" + CAmie + ", CZona=" + CZona + ", CFechaEntrega=" + CFechaEntrega
				+ ", CFechaInicio=" + CFechaInicio + ", CFechaElaboracionInforme=" + CFechaElaboracionInforme
				+ ", sector=" + sector + ", circuito=" + circuito + "]";
	}

}
