package com.capa.datos;
// Generated 29-mar-2017 0:19:52 by Hibernate Tools 4.3.1

/**
 * TFichaD generated by hbm2java
 */
public class TFichaD implements java.io.Serializable {

	private Integer FSerial;
	private TCabecera TCabecera;
	private TInformacionObligatoria TInformacionObligatoria;
	private String FDescripcion;
	private byte[] FFotoFichaD;

	public TFichaD() {
	}

	public TFichaD(TCabecera TCabecera, TInformacionObligatoria TInformacionObligatoria) {
		this.TCabecera = TCabecera;
		this.TInformacionObligatoria = TInformacionObligatoria;
	}

	public TFichaD(TCabecera TCabecera, TInformacionObligatoria TInformacionObligatoria, String FDescripcion,
			byte[] FFotoFichaD) {
		this.TCabecera = TCabecera;
		this.TInformacionObligatoria = TInformacionObligatoria;
		this.FDescripcion = FDescripcion;
		this.FFotoFichaD = FFotoFichaD;
	}

	public Integer getFSerial() {
		return this.FSerial;
	}

	public void setFSerial(Integer FSerial) {
		this.FSerial = FSerial;
	}

	public TCabecera getTCabecera() {
		return this.TCabecera;
	}

	public void setTCabecera(TCabecera TCabecera) {
		this.TCabecera = TCabecera;
	}

	public TInformacionObligatoria getTInformacionObligatoria() {
		return this.TInformacionObligatoria;
	}

	public void setTInformacionObligatoria(TInformacionObligatoria TInformacionObligatoria) {
		this.TInformacionObligatoria = TInformacionObligatoria;
	}

	public String getFDescripcion() {
		return this.FDescripcion;
	}

	public void setFDescripcion(String FDescripcion) {
		this.FDescripcion = FDescripcion;
	}

	public byte[] getFFotoFichaD() {
		return this.FFotoFichaD;
	}

	public void setFFotoFichaD(byte[] FFotoFichaD) {
		this.FFotoFichaD = FFotoFichaD;
	}

}
