package com.capa.datos;
// Generated 28-mar-2017 16:36:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TLugarGeografico generated by hbm2java
 */
public class TLugarGeografico  implements java.io.Serializable {


     private String lgCodigo;
     private TLugarGeografico TLugarGeografico;
     private String lgNombre;
     private Set TLugarGeograficos = new HashSet(0);
     private Set TCabeceras = new HashSet(0);

    public TLugarGeografico() {
    }

	
    public TLugarGeografico(String lgCodigo) {
        this.lgCodigo = lgCodigo;
    }
    public TLugarGeografico(String lgCodigo, TLugarGeografico TLugarGeografico, String lgNombre, Set TLugarGeograficos, Set TCabeceras) {
       this.lgCodigo = lgCodigo;
       this.TLugarGeografico = TLugarGeografico;
       this.lgNombre = lgNombre;
       this.TLugarGeograficos = TLugarGeograficos;
       this.TCabeceras = TCabeceras;
    }
   
    public String getLgCodigo() {
        return this.lgCodigo;
    }
    
    public void setLgCodigo(String lgCodigo) {
        this.lgCodigo = lgCodigo;
    }
    public TLugarGeografico getTLugarGeografico() {
        return this.TLugarGeografico;
    }
    
    public void setTLugarGeografico(TLugarGeografico TLugarGeografico) {
        this.TLugarGeografico = TLugarGeografico;
    }
    public String getLgNombre() {
        return this.lgNombre;
    }
    
    public void setLgNombre(String lgNombre) {
        this.lgNombre = lgNombre;
    }
    public Set getTLugarGeograficos() {
        return this.TLugarGeograficos;
    }
    
    public void setTLugarGeograficos(Set TLugarGeograficos) {
        this.TLugarGeograficos = TLugarGeograficos;
    }
    public Set getTCabeceras() {
        return this.TCabeceras;
    }
    
    public void setTCabeceras(Set TCabeceras) {
        this.TCabeceras = TCabeceras;
    }




}


