package com.capa.datos;
// Generated 28-mar-2017 16:36:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TLugarGeografico generated by hbm2java
 */
public class TLugarGeografico implements java.io.Serializable {

	private String lgCodigo;
	private String TLugarGeografico;
	private String lgNombre;

	public TLugarGeografico() {
	}

	public TLugarGeografico(String lgCodigo) {
		this.lgCodigo = lgCodigo;
	}

	public TLugarGeografico(String lgCodigo, String TLugarGeografico, String lgNombre) {
		this.lgCodigo = lgCodigo;
		this.TLugarGeografico = TLugarGeografico;
		this.lgNombre = lgNombre;
	}

	public String getLgCodigo() {
		return this.lgCodigo;
	}

	public void setLgCodigo(String lgCodigo) {
		this.lgCodigo = lgCodigo;
	}

	public String getTLugarGeografico() {
		return this.TLugarGeografico;
	}

	public void setTLugarGeografico(String TLugarGeografico) {
		this.TLugarGeografico = TLugarGeografico;
	}

	public String getLgNombre() {
		return this.lgNombre;
	}

	public void setLgNombre(String lgNombre) {
		this.lgNombre = lgNombre;
	}
}
